when:
  - event: [push, tag, cron, manual]

steps:
  build:
    image: coralhl/woodpecker-buildx-plugin
    privileged: true
    settings:
      repo: coralhl/sshpiper
      username:
        from_secret: dockerhub_username
      password:
        from_secret: dockerhub_password
      dockerfile: Dockerfile
      platforms:
        - linux/amd64
        - linux/arm64
      tags:
      - latest
      - 1.4.4